### ISSUE TITLE
Which API are you going to use?

### ISSUE THREAD

**Issue by rolandoldengarm** [filfat/swiftsnapper#1]
I'm happy to help, but as far as I know, there is no public API for Snapchat. How are you going to do this?

**Comment by filfat** [comment]
Hi,

I have yet to decide if we're going for Casper.io's public API (which seems to be down at the moment) or if we'll have to reverse engineer the API ourselves.

However, having RE the API ourselves feels like wasted efforts as @liamcottle already got that covered; I'll swing him an email about this project shortly.


Cheers :)

**Comment by The-Bytemaster** [comment]
It is probably a better approach to use the documents that someone else created without reverse engineering the protocol by those contributing directly to this project.  Then you end up with a "clean room" implementation, which ends up avoiding a lot of legal entanglements.

**Comment by ChrisProlls** [comment]
Maybe this API could help : 
- https://github.com/msaville8/snapchat/tree/master/Snapchat

**Comment by filfat** [comment]
@ChrisProlls Sadly not,
That relies on a long outdated API spec. Heck even the more recent ones from September last year doesn't even fully work.

**Comment by ChrisProlls** [comment]
I see :) One more question : why Cordova and not UWP app ?

**Comment by filfat** [comment]
@ChrisProlls UWP stands for "Universal Windows Platform" which is one of Cordovas targets. The reason I went with Cordova instead of ex winjs or .net is purely on preference as I have more experience working with Cordova :)

**Comment by ChrisProlls** [comment]
Ok :) I will give a try if I find enough time, if you allow me to do so.

**Comment by filfat** [comment]
@ChrisProlls Feel free, I need all help I can get :)
(The more people, the better; kind of)

**Comment by filfat** [comment]
Alright, I have decided to use a mix of Casper's and Snapchat's API (basically recreating Casper).
