### ISSUE TITLE
Snaps' list doesn't show up

### ISSUE THREAD

**Issue by lambrikos** [filfat/swiftsnapper#100]
I downloaded swiftsnapper's version that i couldn't see my snaps but just a list. When i downloaded the latest version that everybody talks about because you can finally see your snaps, my snaps' list doesn't show up anymore

**Comment by mentos1386** [comment]
Version they were talking about was https://ci.appveyor.com/project/filfat/swiftsnapper/build/0.1.141 which doesn't work anymore (i think) because of API problems.

**Comment by vitorhbo** [comment]
After log in cannot view the snaps received.

**Comment by Hrishi1999** [comment]
Same problem,any fix?

**Comment by filfat** [comment]
Same as #102
