### ISSUE TITLE
settings error

### ISSUE THREAD

**Issue by gherb** [filfat/swiftsnapper#108]
![wp_ss_20160120_0001](https://cloud.githubusercontent.com/assets/16702528/12443315/56f47398-bf57-11e5-8483-e78efdaf07c7.png)

I have a swiftsnapper logo enlargement when hitting the settings button? It wasnt there in previous builds.
Cheers

**Comment by rphlcristian** [comment]
I'm sorry for what happened , I'm already packing

**Comment by filfat** [comment]
Doesn't happen to any of my test devices anymore, will close this for now.
