### ISSUE TITLE
List doesn't show up

### ISSUE THREAD

**Issue by Hrishi1999** [filfat/swiftsnapper#113]
I opened it. Logged in (crosschecked), no SNAPS! This happens many times. Any help?

**Comment by YBTD** [comment]
something I also had on my Lumia 950

**Comment by filfat** [comment]
You're not even supposed to be able to login after the recent api change. Hmmm... Weird.

**Comment by YBTD** [comment]
I could login, but then there is nothing. Could take a snap but the frame of the camera is not as large as my screen.

**Comment by trischmateus** [comment]
I can login too, idk why, but my login its normal..

**Comment by pvrs12** [comment]
It's a pseudo-login. You're just past the screen, not actually logged in
