### ISSUE TITLE
Downloading the app

### ISSUE THREAD

**Issue by TravisTritt** [filfat/swiftsnapper#120]
Am I just being stupid or am I missing some easy way to be able to get this snapchat client onto my phone and am I mistaken that it is just a snapchat app for windows? Can anyone help with how to install it as really want to try it out!

**Comment by ericbsantana** [comment]
Are you using W10M? You have to put your phone on developer mode, download the appx, transfer the file, open it on your cellphone "file explorer" app, install it and voilà.

**Comment by TravisTritt** [comment]
Sorry for stupid questions but I have a Nokia Lumia 640 and would like to know how to turn it onto developer mode and also if the name of the file i need is CordovaApp.Windows10_1.0.0.0_arm_debug.appx

**Comment by pvrs12** [comment]
Settings > Search > Developer

Also note, almost 0 features are implemented yet, it's still very much pre-alpha

**Comment by TravisTritt** [comment]
Sorry cant find it when i search developer nothing comes up thnx for help guys  XD

**Comment by pvrs12** [comment]
No menu called "For Developers"? Hmm, weird

**Comment by TravisTritt** [comment]
No I do have a Nokia Lumia 640 if that makes a difference any other suggestions?

**Comment by pvrs12** [comment]
Nope. Are you sure you have the W10 preview installed?

**Comment by TravisTritt** [comment]
Oh thats it I need Windows 10 preview! Can windows 10 preview cause any damage that a factory reset could not fix?

**Comment by pvrs12** [comment]
You *can*, but it is **far** from a clean/polished OS right now. You can revert with the tool [here](http://wmpoweruser.com/use-nokia-software-recovery-tool-to-recoverresetrestore-your-lumia-windows-phone-device/) if you need, but you'll lose all your local data.

**Comment by M0A0X** [comment]
just a last question on this subject... I didn t get what I needed to do t instal the app I have a nokia lumia 930 w/ w10 and developer mode but where can I download the app and where should I install it for me to install it on my phone ? (sorry for stupid question :/) thx

**Comment by trischmateus** [comment]
Go to the subreddit, there show how to download and install
