### ISSUE TITLE
Cannot build SwiftSnapper

### ISSUE THREAD

**Issue by Ticomware** [filfat/swiftsnapper#121]
Hello, I am a C# programmer primarily but I'm very familiar with the WinRT/UWP API so I thought I could help contribute to the project. However, I can't get SwiftSnapper to compile. The compiler complains that the "www/cordova.js" file is missing. It fails every time, reguardless of which platform I select. I am using Visual Studio 2015 Community Edition with the Tools for Apache Cordova extension.

This is my first time using Github.

**Comment by ericbsantana** [comment]
This question may be stupid (PROBABLY) but, did you git clone filfat/swiftsnapper repo?

**Comment by Ticomware** [comment]
Yes. I used the "Open with Visual Studio" button on the repo's home page, then cloned and synced the project.

**Comment by ericbsantana** [comment]
Hmm... I used TortoiseGit (https://tortoisegit.org/) to clone the repo, and didn't gave me any error. Perhaps Visual Studio didn't clone www/cordova.js? I think you should try using Tortoise

**Comment by Ticomware** [comment]
But there is no www/Cordova.js stored on the repo at all. Visual Studio got the project just fine. I'm thinking this maybe a WinJS project, but Visual Studio recognizes it as an Apache Cordova project. From what I've been able to gather, the Cordova.JS file (in an Apache Cordova program) is created when its compiled because it's different for each platform.

**Comment by pvrs12** [comment]
Well I wrote an email response, but apparently that didn't work. 

I think I had a similar issue when I first cloned and built it. If it is the same issue then what I remember doing (it was a bit ago) was downloading Node 4.2.6 LTS (with npm) and using that to install cordova (`npm install -g cordova`). Hope this helps

**Comment by Ticomware** [comment]
@pvrs12 Funny you say that, I too wrote an email response and it didn't work.

Anyways, I installed the latest stable version of Node.js (4.2.6 LS) off their website and it works now, thank you so much @pvrs12 !
