### ISSUE TITLE
Being Windows 10

### ISSUE THREAD

**Issue by TravisTritt** [filfat/swiftsnapper#126]
I was wondering if and when this app (which seems sooo good by the way X D) if ever would be able to go onto windows 8.1 phones as I am afraid that upgrading to windows 10 from windows insider will break my 5 days old new phone.

**Comment by pvrs12** [comment]
It's possible. Cordova does allow for building for wp8, but it is non-trivial to sideload that app (need a developer account and to unlock your phone). Don't worry about it right now though, SwiftSnapper doesn't have enough features to bother with

**Comment by TravisTritt** [comment]
Oh ok thanks, do you know how long until it comes out?

**Comment by pvrs12** [comment]
There is no timeline. Development is halted right now waiting on another project that this one needs to work.

**Comment by ericbsantana** [comment]
omg 6 months? that's too muchhh

but we have to wait :sob:

**Comment by pvrs12** [comment]
That's total  by the way. It's 100% dependent on the Casper API. If things go well with it, it could be less. Things go poorly...

**Comment by filfat** [comment]
This project currently relies on a lot of Win10 apis; I see no use backporting to an old version.

**Comment by alejandroRgonzalez** [comment]
So has development come to a complete halt?

**Comment by filfat** [comment]
@alejandroRgonzalez no. Also theres and api available now; however the prices for an oss project like this would be Ludacris, so it'll take a bit more time.

**Comment by christurek** [comment]
Couldn't you just use the iOS to windows 10 objective c converter, change the logos and names of everything and have us sideload it? Also wouldn't doing that convert an API for windows 10 use?

**Comment by codywtworld** [comment]
@christurek agreed.

**Comment by Ticomware** [comment]
@christurek No. We don't have access to Snapchat's iOS source code, only its encrypted binary.

**Comment by Ahuge** [comment]
@Ticomware correct.
@codywtworld @christurek if we had access to the source code for their apps, we wouldn't need Liam, the problem is, Snapchat doesn't want us to use their services, Liam found a way to mimic them near perfectly through lots of his hard work.
No one on this project is nearly as experienced at figuring out whats going on behind the scenes and replicating it as Liam is.
