### ISSUE TITLE
Funding for Casper API

### ISSUE THREAD

**Issue by pvrs12** [filfat/swiftsnapper#130]
So Casper has updated the API and re-allowed registrations https://developers.casper.io

Technically this means that development can easily continue, but the new API is using a rate limited format (which is totally reasonable for Liam to do). 

This new format limits rates according to the following table

Cost ($/month)| Rate (requests/hour)
---|---
100| 100
250| 250
500| 500
1000| 1000
2000| Unlimited

The issue for this project is the budget is 0. There isn't any funding and certainly not enough to support the number of users that I'm estimating we'll get

**Does anyone have any ideas for funding the Casper API?** 

(note this is pretty much a direct copy of [this post on reddit](https://www.reddit.com/r/swiftsnapper/comments/46fxhr/new_casper_api_info_and_request_for_ideas/))

**Comment by Thomasfda** [comment]
Yes but it is very expensive

**Comment by Ahuge** [comment]
What are community's thoughts on banner ads?  I haven't into much could from, so might be viable.  If I get a positive response to this I could look into how many ads we would have to have

**Comment by Ahuge** [comment]
Err we might not be able to have ads since we are not in the windows store. We'll have to look into that too

**Comment by MuriloPereira2015** [comment]
Maybe donations and advertising can help us

**Comment by pvrs12** [comment]
This plugin for Cordova claims to support Google adMob ads for all platforms

https://www.npmjs.com/package/cordova-plugin-admob

**Comment by jeanluc162** [comment]
I'd suggest Adds too. It shouldn't be to difficult to put them in places where they don't interfere with the Apps functionality, should it?

**Comment by christurek** [comment]
If you're expecting a large amount of traffic use it to your advantage. Use advertisements.

**Comment by SharkChips** [comment]
Another idea is to require payments via paypal or some other service.

However, something to note is that whatever method we use, anyone can simply delete the code controlling it (or disable the methods or something) via the source code.

Then and again, this probably not be a huge problem as most people (99%) wouldn't bother to compile the app themselves

**Comment by MuriloPereira2015** [comment]
Wll, to earn money, SwiftSnapper can't be open source, if still be open, just donations will work "/

**Comment by SharkChips** [comment]
@MuriloPereira2015 That's not true. First of all, 99% of users won't bother to recompile the app nor will the know how to remove the advertizing/donations/whatever. Second of all, the entire app right now would have to be rewritten if it were made closed-source, as the SwiftSnapper code base is currently licensed under GPLv3

**Comment by pvrs12** [comment]
It might also be possible to add a clause to the license which prohibits changing the monetary portions. Not sure if it's possible to even change at this point though

**Comment by MuriloPereira2015** [comment]
I agree with @pvrs12 add a clause is a nice idea

**Comment by Ahuge** [comment]
So I tried to find the payout rates for google admob. And it's not as simple as a number...

This article:https://www.scirra.com/forum/what-is-admob-average-pay-per-click-and-earnings_t95243
said it is about $1/1000 imporessions
but others have said it varies greatly.

**Comment by pvrs12** [comment]
That seems pretty low for what we need. Especially considering that the best way to have more impressions is more users, and more users means we need a bigger plan from Casper

**Comment by Ahuge** [comment]
I am assuming that quite quickly we will need the unlimited

**Comment by Ahuge** [comment]
An option might be to try to get some company looking to advertise to Windows Phone users (us) to *Sponser* the app, helping us pay for whatever we are short after our advertising revenue. And hopefully, as we grow, their support will be less needed, although I would propose that we keep their name/logo somewhere big as a thank you.

**Comment by pvrs12** [comment]
I like the idea, but have absolutely no clue what company would want to support this

**Comment by Ahuge** [comment]
Maybe http://www.mobilenations.com/
or http://winsupersite.com

Idk though, you're right it's going to be hard to get a company that is invested in windows phone enough to help us out.

**Comment by Ahuge** [comment]
What if we offered them some service, allowed them to get automatically friended with users of Swiftsnapper, so their snaps show up as sponsored snaps

**Comment by pvrs12** [comment]
Ehh, maybe. I wouldn't recommend it as a Snap, but as a story though. Snaps are (in standard snapchat) reserved for friends (and Team Snapchat). Stories can (and do) come from anywhere.

another possible site
http://mspoweruser.com/

**Comment by pvrs12** [comment]
Also, check out this poll if you haven't already
https://www.reddit.com/r/swiftsnapper/comments/46gnv1/casper_donation_poll_click_here_to_vote/

**Comment by Ahuge** [comment]
Ah neat, I don't reddit as often as I should, I hadn't seen that.

**Comment by Ahuge** [comment]
Also, stories are what I meant, my snapchat vocab isn't perfect haha

**Comment by Ahuge** [comment]
Renaming to Funding for Casper API

**Comment by christurek** [comment]
Windowscentral.com

**Comment by Ahuge** [comment]
mobilenations owns windowscentral

**Comment by Riegusto** [comment]
What I think is strange about this paying thing for using Casper API is that snapchat allows him to do so... he is making money by creating his own API to communicate with there servers. Anyway, secondly I don't get why he doesn't actively helps developing Swiftsnapper, it could be so beneficial for him to just re brand it to casper for windows. Than he has ios, android and windows platform. I think we should try to re open the debate wit @liamcottle.

**Comment by Ahuge** [comment]
I don't think Liam is interested in an open source solution. I don't see how making an app for Windows phone is more beneficial than $2000/month from our project.

**Comment by madsaune** [comment]
To be honest I dont think this project will be able to fund $2000/month (maybe for a while, but not in the long run), so he probably gets close to nothing.

I think the main reason he's not wanting in on this project is because he dont want to piss of Snapchat even more. He has already created a "competitor" and is now making money off of their service, which they probably spend an significant amount of money to maintain.

What he could do tho is silently give us free access and let us keep the name Swiftsnapper :)

**Comment by Riegusto** [comment]
Specter a snapchat client in the store!!! The downside is that we need to pay... THE POSITIVE THING IS THAT IT IS IN THE STORE AND NOT YET HAS BEEN DELETED 😆 - https://www.microsoft.com/store/apps/9nblggh5kldb

**Comment by hypertime123** [comment]
Try creating the app in xcode then porting it to windows 10...or snapchat source code if possible for ios, so tht it can be ported

**Comment by pvrs12** [comment]
We don't have access to snapchat source code (if we did things would be a lot simpler) so we can't do that unfortunately.

**Comment by filfat** [comment]
Perhaps we could come to an agreement with Liam to offer smaller rate limits for cheaper and have the user buy their own personal api key. This way we could keep SwiftSnapper OSS and those who prefer it over Spectre can simply buy an api key.

**Comment by filfat** [comment]
Of course I would much rather keep SwiftSnapper free to use and find another way, but it would be a great solution for now.

**Comment by hypertime123** [comment]
So how would people pay?

**Comment by filfat** [comment]
Taken from the Casper developer portal

> For those of you with smaller projects, such as Community Stories where you only need one Snapchat account to access the API, I will soon be offering cheaper prices where you can have access on a per username basis. At this stage, it's not available, however it's something I'm working on. You will be able to submit a Snapchat Username that can access the Casper API with your API Key and API Secret, without the monthly, rate limit based prices. This will also allow you to test the API while developing your Project rather than purchasing an unlimited rate limit package straight away. Keep watch... It's coming soon :)

**Comment by codywtworld** [comment]
I e-mailed liam after searching his developer page and he said he can't make casper free as the servers needed aren't free. I e-mailed him in an exchange of free servers for access to casper (or snapchat). Hopefully he will respond and we can get this project on the road again.

**Comment by RoboMWM** [comment]
As per my reddit comment:

> Trial + Ads. Since I consider snapchat to be more of a social network/entertainment gimmick I'm totally fine with it having ads, and having use limited - probably a limit per day perhaps? That way you can also keep the amount of requests down.

Although the above two comments look promising.

**Comment by filfat** [comment]
Still waiting for http://developers.casper.io/pricing.php#pricing-username

**Comment by filfat** [comment]
https://gitter.im/filfat/swiftsnapper?at=57872392d11cd288120d4e02
