### ISSUE TITLE
Possible solution?

### ISSUE THREAD

**Issue by codywtworld** [filfat/swiftsnapper#133]
When the project got put on hold I started making my own open source snapchat API and client (separate from snapchat's servers). I have it currently working with sending and receiving snaps, adding friends, accepting friends, logging in, registering, etc. It's all open source (except the web server) and I am actively developing it since us WP users don't have a snapchat client. I guess this could be used as an alternative for Snapchat until something comes out.

App: https://github.com/InZernetTechnologies/PicLoc-Windows
API: https://github.com/InZernetTechnologies/PicLoc-API (The API is documented in the WIKI)

**Comment by Ahuge** [comment]
Hey that's awesome, I'm on mobile at the moment but I'll compile it and give it a test soon.

**Comment by codywtworld** [comment]
@Ahuge Awesome, let me know if you have any issues, I'm currently redesigning the entire thing to make it look better and function better

**Comment by Ahuge** [comment]
So do you have a closed source way to communicate with Snapchat's servers?

**Comment by Ahuge** [comment]
Also do you have a gitter channel we could chat in?

**Comment by codywtworld** [comment]
@Ahuge I don't have a gitter channel. I have skype though

**Comment by Ahuge** [comment]
@codywtworld alright, uh add ahuge.ca on skype. I'm probably going to remove my name from this comment after you add me so i don't get spam

**Comment by codywtworld** [comment]
@Ahuge Added

**Comment by pvrs12** [comment]
So as I understand this, it is *not* a SnapChat client nor is it a service to aid in logging into SnapChat servers (like Casper), but a separate photo messaging app entirely. 

Not sure how this really helps solve our problems; people don't use SnapChat because it is the best solution, they use it because that's what their friends use. Your app might be a lot better than SnapChat, but it'll never take off without a userbase

**Comment by codywtworld** [comment]
@pvrs12 I totally agree with you, I was just trying to offer a disappearing image solution for Windows Phone (Windows 10) users

**Comment by pvrs12** [comment]
Definitely no small feat to do, but it's looking decent so far. 

You should check out [WindUp](https://www.microsoft.com/en-us/store/apps/windup/9wzdncrfjbk8). Similar goal (a little old now), I never tried it so I don't know what the userbase is like

**Comment by codywtworld** [comment]
@pvrs12 Thanks, since the API is openly documented, I hope it would be take off.

**Comment by Riegusto** [comment]
Specter a snapchat client in the store!!! The downside is that we need to pay... THE POSITIVE THING IS THAT IT IS IN THE STORE AND NOT YET HAS BEEN DELETED  😆 - https://www.microsoft.com/store/apps/9nblggh5kldb
