### ISSUE TITLE
Will this thing ever work?

### ISSUE THREAD

**Issue by TravisTritt** [filfat/swiftsnapper#134]
I managed to download this yesterday onto my nokia lumia 520 and was really happy,although then thought wont it just be taken off the store when snapchat owner finds out about it? If i'm wrong please correct me (as I want to be wrong)

**Comment by yemreyazici** [comment]
I think not work. Because developers are not interested

**Comment by wanderkpot** [comment]
Read other Issues #130, #133... And they're interested, but there are some issues with the API and money. Just go after things and read...

**Comment by codywtworld** [comment]
#133 ayeee
