### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by Kcam9908** [filfat/swiftsnapper#136]
I downloaded the most recent build 0.1.193 arm file, and made sure it was the .appx extension. While trying to install, I get an error titles "**Can't install app**," with description of "**There's a problem with this app. Check the package, or contact the person who have it to you for help.**"
This seems to be a problem with the most recent versions, as I was able to install previous builds prior to the most recent update pushes.
I don't know if the dev team means to do this on purpose due to maybe a possibly unstable app, but other people have had this same error. Just thought I would bring this to attention :)

**Comment by ArthurTechWindows** [comment]
Here is ok.

**Comment by yemreyazici** [comment]
App not working

**Comment by filfat** [comment]
Still waiting for http://developers.casper.io/pricing.php#pricing-username
