### ISSUE TITLE
How it can work Specter?

### ISSUE THREAD

**Issue by yemreyazici** [filfat/swiftsnapper#137]
Specter is working. I look stories. I can send snap. Swiftsnapper Why does not work?

**Comment by pvrs12** [comment]
I talked with the developer of Spectre a few weeks ago. He said that he is currently using a reverse engineered endpoint (essentially stealing) to get access to the API. He's looking to do it the right way, but essentially has the same issues that we do right now with how he's going to eventually pay for it when development gets bigger.

**Comment by codyvsworld** [comment]
@pvrs12 I talked to him too, because it works great, just the UI needs to get better.
