### ISSUE TITLE
Created irc channel on freenode.

### ISSUE THREAD

**Issue by Ahuge** [filfat/swiftsnapper#14]
Join swiftsnapper on freenode.

@filfat, I'll make you an op just let me know what your account is.

**Comment by filfat** [comment]
Will do :)

**Comment by mentos1386** [comment]
I think this would be more appropriate https://gitter.im/

**Comment by Ahuge** [comment]
Haha probably true.

**Comment by filfat** [comment]
Yeah gitter would be better :)

**Comment by Ahuge** [comment]
lol

**Comment by danibjor** [comment]
https://gitter.im ;)
