### ISSUE TITLE
hi when i downlode the swiftsnapper tell me this masge!

### ISSUE THREAD

**Issue by esrabh** [filfat/swiftsnapper#140]
http://store2.up-00.com/2016-07/1468957090271.png
Open this ,😒

**Comment by esrabh** [comment]
What's the problem 😢

**Comment by filfat** [comment]
Try reading the readme before asking.

**Comment by esrabh** [comment]
What!I i have a problem in this app

**Comment by Ahuge** [comment]
Literally the first line

"SwiftSnapper is not happening anymore, neither is Specter or even Casper"

**Comment by dreamilk34** [comment]
how i install this app?

**Comment by pvrs12** [comment]
The ReadMe is clear. This app does not work. Attempts to install it are pointless
