### ISSUE TITLE
Camera Preview is rotated 90 degrees to the right

### ISSUE THREAD

**Issue by Ahuge** [filfat/swiftsnapper#15]
Looking into it. I just wanted to post it as a bug.

Let me know if you are on a device that isn't rotated.

**Comment by hypertime123** [comment]
@Ahuge the samething happens with my HTC ONE M8 WINDOWS

**Comment by Ahuge** [comment]
Perfect I was assuming it was happening regardless of device but I have nothing else to test with.

**Comment by hypertime123** [comment]
@Ahuge I'm pretty sure @filfat is aware of this issue, but he went to bed.

**Comment by filfat** [comment]
@hypertime123 I should have, 2 and a half hours till the clock ring... Damn irregular sleep schedule.

**Comment by hypertime123** [comment]
@filfat isnt the camera rotation an easy fix?

**Comment by filfat** [comment]
@hypertime123 should be, just haven't really looked into the docs yet :)

**Comment by pvrs12** [comment]
I fiddled with adding this line to the video preview `mediaCapture.addEffectAsync(Capture.VideoRotation.clockwise90Degrees);` but the zoom is totally off then. I don't know enough JS/CSS to fix it, but I suspect that it can be done

**Comment by filfat** [comment]
@pvrs12 that breaks it on pc though, so we would have to make an specific case for mobile :)

**Comment by Ahuge** [comment]
Looking into mp-cordova-plugin-device.

device.model returns Win32 on desktop and ARM on Mobile.

I'm going to implement that.

**Comment by christurek** [comment]
Rotated 90 degrees on my Lumia 950 for both the front and back cameras

**Comment by Thomasfda** [comment]
The bug is on my Lumia 640 :)

**Comment by christurek** [comment]
Still rotated as of 1.9x build just fyi

**Comment by Ahuge** [comment]
My pull request https://github.com/filfat/swiftsnapper/pull/69 should help fix these. Ill let you know when it is in a build.

**Comment by Thomasfda** [comment]
Fix on last build !

**Comment by filfat** [comment]
It's fixed on Windows 10 Mobile, however on Windows 10 its now rotated (have only tested landscape mode so far)

**Comment by Ahuge** [comment]
Shoot... I don't have a camera for my computer so I don't know how to test this.

**Comment by christurek** [comment]
Picture is now in correct orientation and pictures can now be taken. You should use the accelerometer to check whether it's in portrait or landscape and if no accelerometer is detected, default to landscape for PCs.

**Comment by Ahuge** [comment]
Good idea

**Comment by Ahuge** [comment]
So I made a request that might fix it.... I need @filfat and anyone else with a desktop with a camera to test it for me.

**Comment by filfat** [comment]
@Ahuge what's the value of device.platform on win10 mobile?

**Comment by filfat** [comment]
Also, your fix might work on external web cams; but it doesn't work on my Surface. I have a fix providing that device.platform isn't the same on PC as it is on Mobile.

**Comment by christurek** [comment]
So change the file so that if it's pc it uses the pc version of device.platform and for mobile, it uses the mobile device.platform

**Comment by christurek** [comment]
I don't know coding so I probably no idea what I'm talking about

**Comment by Ahuge** [comment]
##### Desktop vs Phone
console.log(device.model); // Win32  // ARM
console.log(device.platform); // windows  // windows
console.log(device.version); // 10.0.10586.0  // 10.0.10586.36

**Comment by Ahuge** [comment]
Oh! I could be using my surface to test.... my god how did I forget that

**Comment by filfat** [comment]
device.model returns "Surface Pro 2" for me, perhaps I should just check for "Phone" inside the user agent.

**Comment by filfat** [comment]
(explained here https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx)

**Comment by filfat** [comment]
Confirmed to work on both my 1520 and SP2.

**Comment by Ahuge** [comment]
Confirmed to work on my SP2, desktop and Lumia 950XL

**Comment by filfat** [comment]
Prefect :)
