### ISSUE TITLE
Photo taking not implemented

### ISSUE THREAD

**Issue by Ahuge** [filfat/swiftsnapper#21]
Was trying to implement the Take Photo function on the cameraManager class.

Bumped into an issue that I can't seem to overcome.

I was attempting to use:
mediaCapture.getPreviewFrameAsync()

found here:
https://msdn.microsoft.com/en-us/library/windows/apps/dn926712.aspx

But Visual Studio is telling me that I am crazy and getPreviewFrameAsync doesnt exist.

@filfat what was your plan for the take photo function?

**Comment by filfat** [comment]
@Ahuge the definition file for the UWP api is still lacking in some areas. have you tried to reference it using mediaCapture['GetPreviewFrameAsync'](...) ? :)

**Comment by realwarder** [comment]
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CameraStarterKit

Is a nice example with hardware buttons, resolution, rotation etc.

**Comment by azhang66** [comment]
This is a really ugly hack, but on Android the official client simply hides the UI and takes a screenshot. If we can't get photo taking working, maybe that could be a reasonable alternative.

**Comment by Ahuge** [comment]
@realwarder I had been looking at an older version of that. Yet both seem to be using Windows.Graphics.Display.DisplayInformation.getForCurrentView(); to gather information about the orientation and stuff. 
In Javascript Windows.Graphics.Display doesnt seem to have DisplayInformation anymore on it. I'm guessing it has been removed/renamed.

**Comment by filfat** [comment]
@azhang66 We could just take a frame from the preview video using javascript.
(something like http://stackoverflow.com/questions/24208113/capture-video-screenshot-using-canvas)

**Comment by filfat** [comment]
@Ahuge try ```Windows.Graphics.Display['DisplayInformation']``` :)

**Comment by Ahuge** [comment]
Cool that seems to work.

**Comment by Ahuge** [comment]
I've got a build over here: https://github.com/Ahuge/swiftsnapper
That is close to being ready to fix this. I think Ill push it out after work tomorrow, just have one small bug to fix.

Below is what it looks like for me.

![wp_ss_20160112_0002](https://cloud.githubusercontent.com/assets/704821/12259381/30786ea6-b8ca-11e5-9001-bb90ac5b9ff4.png)

**Comment by Ahuge** [comment]
I think size there is just a css issue but I'm not sure

**Comment by filfat** [comment]
Great work; I can't really look into the css issue as it doesn't occur on my 1520, will test on a spare 920 I have laying around :)

Also, Hmm, I need to get a phone with onscreen buttons. It seems like they occupy DOM space.

**Comment by Ahuge** [comment]
Yeah either that or we need to figure out the auto hidding buttons. Not sure how to do that.

Ill try to play around with the css at some point too.

**Comment by Ahuge** [comment]
@filfat Any chance I could get you to test the new build and let me know if your video feed looks correctly rotated still?

Also do you have any idea where I should look to manage the on screen "soft" buttons on newer phones?

**Comment by filfat** [comment]
Yep the video is correct as of the latest build :)

**Comment by Ahuge** [comment]
Woohoo! Maybe it's working for everyone too!
