### ISSUE TITLE
Implement credentials saving

### ISSUE THREAD

**Issue by filfat** [filfat/swiftsnapper#23]
Currently the user have to login each time opening the application,
we could implement credentials saving securely using [Windows.Security.Credentials](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/PasswordVault)

**Comment by MuriloPereira2015** [comment]
I think save the credentials will save a lot of time for users, and do the logon always can muddle push notifications, saving credentials is a great idea!

(Sorry for my english)

**Comment by azhang66** [comment]
@filfat I can work try to work on this

**Comment by filfat** [comment]
@azhang66 Alright :)

**Comment by Riegusto** [comment]
@azhang66 how is your progress on the saving login data? :)

**Comment by homroz** [comment]
We can close this issue, I fixed it with #97
