### ISSUE TITLE
Save received snaps

### ISSUE THREAD

**Issue by MuriloPereira2015** [filfat/swiftsnapper#26]
In the SwiftSnapper will be possible save received snaps without show notification for the sender?

**Comment by jimmyjango** [comment]
This is the reason Snapchat banned 3P solutions in the first place so I recommend not doing this.

**Comment by MuriloPereira2015** [comment]
But if the app go to Windows Store, it will receive an automatic ban, because Snapchat doesn't allow 3rd party apps, and if the app don't go to Windows Store, it's possible put that resource in the app, like Casper.

**Comment by filfat** [comment]
@murilopereia2015 Well, they might not allow 3rd party apps; but without any real legal ground to stand on I could easily fight the take down notice. Not that I see any point in going through that process before we have feature completed SwiftSnapper.

Also no, as of now saving snaps without notifying the other end just gives snapchat yet another reason to hate us.
