### ISSUE TITLE
API tokens in source file

### ISSUE THREAD

**Issue by pvrs12** [filfat/swiftsnapper#3]
What are the API tokens in [snapchat.agent.ts](https://github.com/filfat/swiftsnapper/blob/master/scripts/SC/snapchat.agent.ts)? 

If they're at all legitimate then they *really* shouldn't be in source files in plain text. My recommendation is to remove them and have users supply their own. Additionally, they (if they are the tokens I think they are) provide carte blanch access to whatever account they are associated with, and that usually leads to bad people doing bad things

**Comment by filfat** [comment]
@pvrs12 They're taken from
https://github.com/cuonic/SnapchatDevWiki/wiki/Global-variables

**Comment by KyleMcNutt** [comment]
I would normally agree that it doesn't make sense to have API tokens in plain text in source code, but there are two reasons why I think it makes some sense here.

1. The project is designed so the average WM10 user could side-load the app onto the phone, a user having to generate an API token and drop it in somewhere would be a huge barrier here. Not to mention there is no official way to generate API tokens for Snapcat.

2. The API tokens have already been made public, as was linked to.

The big disadvantage though that I see is that the API tokens are currently hard-coded into the source. Meaning that if the API was to ever be updated or those tokens were to ever expire it would require an update to be made to the source here. Although that is a very minor change, it does mean that user need to download the latest version and update the side-loaded app on their device.

**Comment by pvrs12** [comment]
Ahh, did not know they were static things. Thanks for clarifying that
