### ISSUE TITLE
Frezees at splash screen

### ISSUE THREAD

**Issue by christurek** [filfat/swiftsnapper#34]
The app is stuck at the splash screen and will not allow anyone to log in or use the app on ARM devices.

**Comment by allan991** [comment]
Have you try on Visual Studio?

**Comment by christurek** [comment]
Why would I?

**Comment by christurek** [comment]
Still stuck at splash screen as of latest patch Lumia 950

**Comment by filfat** [comment]
Yep, same happens to me; It seems like the javascript code never gets executed... hmm.

**Comment by Ahuge** [comment]
What os version are you guys on?

**Comment by filfat** [comment]
@Ahuge it only happens with the Appveyor build, perhaps the typescript never gets compiled. Just re-added app.js temporarily to test the theory.

**Comment by Ahuge** [comment]
oh odd.

**Comment by filfat** [comment]
Yep that's the case.

**Comment by filfat** [comment]
It works now. I'll have to look into why that doesn't work on appveyor; but I'll marked this fixed as including app.js isn't really a huge problem :)
