### ISSUE TITLE
Docs for snapchat modules?

### ISSUE THREAD

**Issue by Ahuge** [filfat/swiftsnapper#38]
Hey @filfat in your Snapchat agent PostSnapchat method, what are the parameters needed?

**Comment by filfat** [comment]
Yeah I know the docs sucks (It's on my todo list).
https://github.com/filfat/swiftsnapper/blob/master/scripts/SC/snapchat.agent.ts#L65

Here's a quick example
```javascript
PostSnapchat('/loq/whatever'I, [
  ['paraName1', 'Val'],
  ['paraName2', 'Val']
],{
  'Connection': 'Keep-Alive',
  'User-Agent': '...''
}): 
```

**Comment by Ahuge** [comment]
cool thanks. What about Casper docs?

**Comment by filfat** [comment]
For post, they're essentially the same :)

**Comment by Ahuge** [comment]
nice! thanks

**Comment by Ahuge** [comment]
Started the wiki docs
