### ISSUE TITLE
App crashed after logging

### ISSUE THREAD

**Issue by Aureliink** [filfat/swiftsnapper#40]
Hi !
First, thanks for the hard work and all the efforts you are putting on the app.

I tried the latest version today on my 950XL after you updated the app to be functionnal with the latest W10M build (10586.63) and now the buttons appear correctly.

When I try to log-in, if my Username/Pwd is incorrect, its ok I've got the right message in the box.
But as soon as I put the right credentials, the app crashes.

I know I used 6snap a long time ago and may be (not 100% sure, last time I checked it wasn't the case) my account has been banned and this an error not handled yet. Or it could be something else.

Anyway that's something you could take a look at :-)

**Comment by Thomasfda** [comment]
Yes, a problem report on "Current Statut"

**Comment by filfat** [comment]
Should just have been fixed in the latest commit.
Forgot my usb cable so I did something stupid, coded blindly :P
