### ISSUE TITLE
What vs plugins do I need?

### ISSUE THREAD

**Issue by Ahuge** [filfat/swiftsnapper#6]
I assume cordova but having never developed with cordova before I'm not sure if there are other packages I need as well.

**Comment by filfat** [comment]
Hi,
Visual Studio 2015, Apache Cordoba Tools and git should be everything you need :)

(Ofc, having node.js configured outside Visual Studio too helps)

**Comment by pvrs12** [comment]
I should note that I needed to use node.js v4.2.4 LTS. Not sure if the same will apply to you, but for me builds would fail (from VS) with v5.4.0
