### ISSUE TITLE
My SwiftSnapper Issues // Lumia 535 - Windows 10 Mobile

### ISSUE THREAD

**Issue by a4x2** [filfat/swiftsnapper#61]
Hey @filfat , first thank you for doing this app seriously you are perfect developer:) Secondly Im turkish, so sorry for my english, it can be bad some times

I wanna transfer my experiences during using this app;
1-I know it, but we need to login each time opening the application
2-Camera switching crashes the application
3-Camera (front or back this isn't important) Preview is rotated 90 degrees to the right
4-Stories didn't work?
5-I can't open the snaps
6-Camera can't take the photo?
7-Search, configurations or sending snap is not working too

These are my Issues.And again you are perfect @filfat :) so gonna see you guys in a new build

**Comment by Riegusto** [comment]
@a4x2 you just summed up every single feature that still has to be implemented off witch we are aware. Please first read the other issues and read what this project is about. Than you should have known that submitting this issue was time wasting for you and others...

**Comment by Ahuge** [comment]
Hey @a4x2, I'm going to close this just to remove clutter.

If you have reddit, I'd invite you to talk about this on the official subreddit [here](https://www.reddit.com/r/swiftsnapper/)

In the future, could you check to see if there is already an issue the same as yours? If there is, you can comment in it to let use know that you are also experiencing the problem.
If there is no issue made for your problem yet, please create one issue for each of your problems. This way we can close each one when we complete it.


Thanks @a4x2
