### ISSUE TITLE
Got banned from snapchat

### ISSUE THREAD

**Issue by Riegusto** [filfat/swiftsnapper#67]
@filfat I have been trying lot's of swiftsnapper builds so I did login a lot of times. Now I wasn't able to login anymore so Itthought it was maybe a faulty build so tryed a previous one that normally did work but no success. Than I tried to login using the official Snapchat apk on an android tablet and I couldn't login, got an error message that my account did temporarily fail to login...

**Comment by Maxyeah** [comment]
Maybe it is a result of the, no snapchat apps on wp policy. I hate them. Where is the problem?

**Comment by MuriloPereira2015** [comment]
@Riegusto Check your email, they, probably, sent a message to you with a link to change your password and unlock your account.

**Comment by theboginator** [comment]
A thought for @filfat and other developers to take into consideration, not sure if it's been included in the code, but Snapchat does verify what device you're using and the WP platform will answer incorrectly (if at all) to a device type or id query from a Snapchat server. Therefore, to mask this app from SnapChat's 3rd Party app detectors, including code that tells the servers this is an Android/iPhone device might be worthwhile.

**Comment by Ahuge** [comment]
Huh I thought we were using an Android Useragent. The first few versions of Snapchat.Agent.ts had several different User_Agents
Here is when it got removed.
https://github.com/filfat/swiftsnapper/commit/6c66e52b9a31e5dcb2f3aeb00cb555437d6c42dd

Maybe the old user agents were no longer working?

**Comment by filfat** [comment]
We haven't fully implemented the login flow yet, that's why :)

**Comment by Ahuge** [comment]
haha ok. So we should use a test account to login haha

**Comment by filfat** [comment]
Yes :P
(Also, my testing account have yet to be banned, you haven't happened to use other 3rs party apps?)

**Comment by Ahuge** [comment]
Yeah for what it's worth, mine is fine too

**Comment by Thomasfda** [comment]
My account principal not banned :o

**Comment by filfat** [comment]
I can now confirm that Casper had a few backend problems and that's what caused the outages, I will add an error message for this in the future.
