### ISSUE TITLE
Preview Builds.

### ISSUE THREAD

**Issue by azhang66** [filfat/swiftsnapper#7]
I know this project is still very early im development, but would it be possible to release weekly builds or something so users don't have to download visual studio and compile it themselves?

Anyways keep up the good work☺

**Comment by filfat** [comment]
This could be done via a CI like Jenkins or something, but would mean I'd have to rent a virtual machine in the cloud.

To answer your suggestion yes, automatic builds will be a thing once we have a broader feature set :)

**Comment by sartero** [comment]
It would be a good idea, it will be qn would be possible for you compile a version of the project and level up in a download site? I believe we have many users eager to do some testing in this gorgeous design!

**Comment by azhang66** [comment]
I will see if I can get travis CI working

**Comment by filfat** [comment]
@azhang66 Travis CI doesn't support building in Windows which is required to compile windows applications, ovbs some unit testing could be done in Linux though.

**Comment by azhang66** [comment]
@filfat  https://www.appveyor.com/ appears to support Windows build enviornments

**Comment by azhang66** [comment]
@filfat I've added a build script that makes packages in #19
