### ISSUE TITLE
Owl Carousel what page am I on?

### ISSUE THREAD

**Issue by Ahuge** [filfat/swiftsnapper#71]
Hey @filfat I was looking at the docs and I wasn't able to figure out how to tell where the viewer is on the screen. Because it is a 1 item carousel the index always seems to be 1.

I was looking into adding a backButton event listener to capture back button presses, move you to the middle screen, and if you are already there, exit the app.

But I wasn't able to get the "current" spot in the view

**Comment by pvrs12** [comment]
Hey @Ahuge. It looks like the active page gains the `active` class when it is switched to, but that doesn't really give a clear picture as to which one is selected since they don't have an identifier (at least that I can see)

**Comment by filfat** [comment]
```javascript
views.on('initialized.owl.carousel changed.owl.carousel', function(event) {
        var currentItem = event.item.index;
})
```

The above code will give you a callback with the current item on init and every time it changes,
We could store this in a global variable.

**Comment by Ahuge** [comment]
oh thanks!

**Comment by filfat** [comment]
just found this http://glenngeenen.be/owlcarousel-2-current-item/, you could check if the .active element have a "#CameraView" child for the overviewpage. However providing. Global var with the current page could be useful for future features.
