### ISSUE TITLE
List of received snaps is listed from old to new.

### ISSUE THREAD

**Issue by Riegusto** [filfat/swiftsnapper#78]
As the issue tells, you see your old snaps in the beginning of the list and new ones at the bottom.

@filfat just to let you know. I don't really know sometimes if I should report a bug or not? Or do you want us to report every single one we find?

**Comment by filfat** [comment]
Thanks, I'll quickly fix this by simply reversing the list.

Yes, report all bugs you find just double check that they haven't been reported already :)

**Comment by Riegusto** [comment]
Ok I'm on it 😊

**Comment by filfat** [comment]
Already done :P
