### ISSUE TITLE
Screens

### ISSUE THREAD

**Issue by ruben9696** [filfat/swiftsnapper#88]
Lock the bar to not happen this
![wp_ss_20160113_0001 465841](https://cloud.githubusercontent.com/assets/16638892/12298937/7909fac0-ba0c-11e5-8644-9609d450198c.png)
![wp_ss_20160113_0002 465840](https://cloud.githubusercontent.com/assets/16638892/12298938/795e1fba-ba0c-11e5-9309-c1e0aaa905d9.png)

**Comment by realfakenerd** [comment]
![wp_ss_20160113_0003](https://cloud.githubusercontent.com/assets/16668109/12300289/f2b84e54-ba01-11e5-898e-731a01b12a6e.png)

The buttons on the superior part are not clickable, I clicked but nothing happened.
