### ISSUE TITLE
Change about to occur in Casper API

### ISSUE THREAD

**Issue by filfat** [filfat/swiftsnapper#92]
We're currently accessing Snapchat's API by spoofing the app using Casper, to use Casper however we have to spoof the actual Casper client. Due to recent events there's a bunch of upcoming security challenges on Casper's end which we'll need to address ASAP. https://www.facebook.com/casper4snapchat/posts/1650721461860775

**Comment by Thomasfda** [comment]
Their api becomes unusable... ?

**Comment by ruben9696** [comment]
And now?

**Comment by Djuystick** [comment]
Hum, the end of the Aventure ?

**Comment by gncgabriel** [comment]
What happens from here on out? Is this the end?

**Comment by gncgabriel** [comment]
![wp_ss_20160113_0003](https://cloud.githubusercontent.com/assets/16600779/12307515/da112c84-ba26-11e5-8690-ed4ee4b462e5.png)


This is solution ?

**Comment by gncgabriel** [comment]
@filfat And now? What is the app?

**Comment by filfat** [comment]
I'm working on it

**Comment by filfat** [comment]
Ping @liamcottle would be awesome if you could read & respond to the email i sent you :)

**Comment by pvrs12** [comment]
Is Casper a necessity? I know it helps with the logins, but can't they simply be implemented via the static token, then client token passing like describe [here](http://gibsonsec.org/snapchat/fulldisclosure/#creating-static-tokens) and implemented [here](https://github.com/mgp25/SC-API)

**Comment by craycraycoco** [comment]
@pvrs12 The implementation still uses casper, and the SC-API isn't currently updated (to my knowledge)

**Comment by pvrs12** [comment]
@craycraycoco Oh, duh. I didn't read it enough...

**Comment by christurek** [comment]
Did this get fixed

**Comment by filfat** [comment]
@christurek only temporarily; We're required to switch to the new API by next week.

**Comment by Ahuge** [comment]
Hey @filfat when you emailed him did you use one of his predefined subject titles from here?
https://www.liamcottle.com/contact

**Comment by filfat** [comment]
@Ahuge yep

**Comment by filfat** [comment]
https://itunes.apple.com/us/app/snap-hack-lite-for-snapchat/id782424957?mt=8 Seems to still work; perhaps they have figured out how to generate the X-Snapchat-Client-Auth-Token & X-Snapchat_UUID headers. I'll try to capture it's traffic later today.

**Comment by Thomasfda** [comment]
It's possible ?

**Comment by christurek** [comment]
liam said he'd get back to you as soon as he could. Hold tight

**Comment by Ahuge** [comment]
hype

**Comment by Thomasfda** [comment]
Liam back ? For Swift ?

**Comment by Riegusto** [comment]
![casper](https://cloud.githubusercontent.com/assets/8606215/12322810/cd001c22-bab6-11e5-85f2-6850bae34b8f.png)

@filfat I did send him this yesterday, so he should reply soon...

**Comment by Thomasfda** [comment]
Humm.. Cool If it is positive

**Comment by filfat** [comment]
Awesome! :D

**Comment by Riegusto** [comment]
@filfat in the mean time is build 0.1.141 still working for me, so nice to just watch my new received snaps :D :+1:

**Comment by filfat** [comment]
Liam's response.

```
Hi Filiph,

Great to see someone working on another Windows Phone app for Snapchat!

Unfortunately right at this point in time, my Public API has been taken offline, due to a few reasons, the first being that it runs off the Android API.

The Snapchat Android API can't be used at this stage by third party applications, as it requires some data from Google servers which can't be retrieved by devices with the Xposed Framework, which we used in order to spoof a few things, which Google has now patched... In turn causing that route to no longer work.

As for the iOS Snapchat API, this requires Client Tokens and Client Auth Tokens for logins and each endpoint request.

Due to how this works (my backend, which I can't disclose the operation techniques of), I can't open it up to the public at this stage.

The main reason I can't do this, is due to the traffic load, which causes quite a few issues for myself and how the backend works.

I have quite a few other developers wanting access to my Private API's used in Casper, but as I said I can't allow that just yet, hence why I've added the extra security in the latest update, to prevent access to it...

If I do build and release a Public API, I'll make a post on the Casper Facebook page, so make sure to follow that for updates on the API etc.

I do plan to build a public API, however as I said, not just yet.

Cheers,
Liam Cottle```

**Comment by craycraycoco** [comment]
@filfat is it possible to develop a way into snapchat's API without the use of Casper? That seems like the only way that SwiftSnapper is going to work now.

**Comment by Thomasfda** [comment]
Oh... can not find another solution? The end?

**Comment by MuriloPereira2015** [comment]
If split developers in 2, for example, as mentioned above, has yet a build running, a part could use it to develop other app resources while another search or creates an way to generate the tokens and implement in SwiftSnapper

Sorry for my english

**Comment by christurek** [comment]
What's the solution? Work in conjunction with Casper to deliver a w10m version?

**Comment by Riegusto** [comment]
@christurek I like the Idea, casper for W10 & W10M would be nice for us and some more credit for @liamcottle.

**Comment by eDameXxX** [comment]
Hi @filfat What’s the current status of the project?

**Comment by filfat** [comment]
@eDameXxX not the place to discuss that. See #2
