### ISSUE TITLE
Cannot login after build 0.1.141

### ISSUE THREAD

**Issue by madsaune** [filfat/swiftsnapper#93]
Cannot login after installing 0.1.141. Tried rebooting.

Sits at "Logging in..." then app closes after a few seconds.

Ref device Lumia 930.

Can login on my Android device with the same user.

**Comment by juanaleixo** [comment]
Have this same problem in 640

**Comment by Riegusto** [comment]
@filfat the same here, after you added the option to go back from a snap you where watching I was not able to login anymore.

**Comment by Djuystick** [comment]
Same on my Lumia 930

**Comment by a4x2** [comment]
Same on my Lumia 535

**Comment by christurek** [comment]
I think its the Casper problem causing this

**Comment by Riegusto** [comment]
it has to be, cuz I tried previous version and wasn't able to log in where i previously could...

**Comment by gooomis** [comment]
Yup, same here, L930 10586.63

**Comment by Djuystick** [comment]
yep, because casper was change her API

**Comment by Riegusto** [comment]
I was able to login again! :D

**Comment by Riegusto** [comment]
@filfat also the latest built was working now, I could watch a snap and was able to go back to the snap menu. It is only not clear to me where I need to klick to open one. I just tap it 100 times and al of a sudden it opens after som time :p
